# Generated by Django 3.1.4 on 2021-01-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_checkcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checkcode',
            new_name='Check',
        ),
    ]
