# Generated by Django 3.1.4 on 2021-01-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20210124_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='session_data',
            field=models.TextField(),
        ),
    ]
