# Generated by Django 3.1.4 on 2021-01-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20210124_0029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Check',
            new_name='CheckCode',
        ),
    ]
