# Generated by Django 3.1.4 on 2021-01-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_auto_20210124_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_no', models.IntegerField(max_length=11)),
                ('term_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tbl_term',
                'managed': True,
            },
        ),
    ]
