# Generated by Django 3.1.4 on 2021-01-24 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210124_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
