# Generated by Django 3.1.4 on 2021-01-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0004_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=30)),
                ('stu_sex', models.CharField(choices=[(1, '男'), (2, '女')], default=2, max_length=1)),
                ('stu_gdu', models.CharField(max_length=30)),
                ('stu_bth', models.DateField()),
                ('stu_id', models.CharField(max_length=18)),
                ('stu_tel', models.CharField(max_length=11)),
                ('stu_pol', models.CharField(choices=[(1, '共青团员'), (2, '共产党员'), (3, '入党积极分子'), (4, '其他党派'), (5, '群众')], default=1, max_length=6)),
                ('stu_dpt', models.CharField(max_length=2)),
                ('stu_class', models.CharField(max_length=8)),
                ('stu_sta', models.CharField(choices=[(1, '在校'), (2, '离校')], max_length=4)),
                ('stu_pwd', models.BinaryField()),
            ],
            options={
                'db_table': 'tbo_student',
                'managed': False,
            },
        ),
    ]
