# Generated by Django 3.1.4 on 2021-01-24 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True},
        ),
    ]
