# Generated by Django 3.1.4 on 2021-01-24 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210124_1118'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='tbl_student',
        ),
    ]
