# Generated by Django 3.1.4 on 2021-01-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_checkcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckCode',
        ),
    ]
